import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// layout page inserts html in the next app

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//server rendering is code is generated at server side, unlike react
export default function RootLayout({
  children, product //for dynamic route product
}: {
  children: React.ReactNode
  product: React.ReactNode//for dynamic route product
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        
      </body>
    </html>
  )
}
